### ISSUE TITLE
使用 yazl 有bug，请使用 archiver

### ISSUE THREAD

**Issue by maxming2333** [fex-team/fis3-deploy-zip#3]
使用 `fis3-deploy-zip` 打包出来滴zip文件

项目中遇到后端java zip解压库无法解压，

mac下解压软件报错

经过几番论证，终于确定是 `yazl` 问题，

直接写一个压缩函数，使用 `archiver`

发现mac下解压软件正常，java 解压正常

`archiver`项目地址 : [https://github.com/archiverjs/node-archiver](https://github.com/archiverjs/node-archiver)

请速度确认此 bug

**Comment by 2betop** [comment]
先用 `.tar.gz` 把，我来看下 zip 的问题

**Comment by 2betop** [comment]
用这个版本试试 fis3-deploy-zip@2.0.0

**Comment by maxming2333** [comment]
还没测试，目前项目需要压缩都是自己写插件压缩了

这个晚上我测试一下

**Comment by 2betop** [comment]
好的，辛苦

**Comment by maxming2333** [comment]
这个issues加个 `bug` 的tag吧

**Comment by maxming2333** [comment]
已验证

**Comment by 2betop** [comment]
ok，那是没问题吧，没有的话，就 close 掉把。

**Comment by maxming2333** [comment]
恩，可以close了
